# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

# Repo: Contoso/WindowsProduct
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: templates
      type: github
      name: schmidtjohannes/azure-devops-build-templates
      ref: refs/tags/v1.0 # optional ref to pin to
      endpoint: schmidtjohannes
jobs:
#- template: common.yml@templates  # Template reference
#  parameters:
#    vmImage: 'vs2017-win2016'
- job: Install Package
  steps:
  - script: echo My first job
